### ISSUE TITLE
Write inside the donut chart

### ISSUE THREAD

**Issue by MariusGarbea** [chartist-js/chartist#674] opened 2016-04-16 11:03 UTC
I want to write something inside the donut chart. I came with an unorthodox solution and I am sure that there is something better out there (basically added a 0 value to series and labeled it). http://codepen.io/ananasqwer/full/ZWreyE/

I would also like to display only the label inside the donut chart. Thanks!

**Comment by joshiste** [comment] 2016-04-17 21:00
My approach to this problem is to add a centered `div` behind the svg with the same extents as the donut (cause I needed wrapped text and this is a bit tedious with svg). The text even get updated when hovering over the slices.

**Comment by gionkunz** [comment] 2016-10-19 09:59
Duplicate of #255

**Closed as completed by gionkunz** 2016-10-19 09:59 UTC
