### ISSUE TITLE
Follow-up to Access totals in stacked bar chart (#238)

### ISSUE THREAD

**Issue by akhasis** [chartist-js/chartist#317] opened 2015-05-13 06:53 UTC
Regarding the forementioned topic, I provided new details and code.

My example at http://jsbin.com/yajixayeqi/edit?html,js,output is very simplified (the actual chart has more than 20 bars) so please let me know if I let out any important piece of info.

Sorry to open a new topic, couldn't find the way to reopen the old one or contact gionkunz privately to do so.

**Comment by gionkunz** [comment] 2015-05-13 08:27
Hi there

This is a general data processing issue as with stacked bars this is not as simple as it seems in the first place. The problem is that stacking bars is ripping the series apart and grouping them into a separate group of data that does not easily map to the original data. You need to calculate the total stack bar value by summing each of the values for each series based on the value index.

The second problem is how to make this available in the DOM. Chartist allows you to specify a meta property on series but also on values that will be transferred into the DOM as a `ct:meta` attribute.

Technically you'd need to put the stack total manually for each value so this:

``` javascript
series: [
    { 
      name: 'Finished',
      data: [1, 2, 3]
    },
    {
      name: 'Ongoing',
      data: [1, 2, 3]
    },
    {
      name: 'Not started',
      data: [1, 2, 3]
    }
]
```

would become this:

``` javascript
series: [
    { 
      name: 'Finished',
      data: [{value: 1, meta: 3}, {value: 2, meta: 6}, {value: 3, meta: 9}]
    },
    {
      name: 'Ongoing',
      data: [{value: 1, meta: 3}, {value: 2, meta: 6}, {value: 3, meta: 9}]
    },
    {
      name: 'Not started',
      data: [{value: 1, meta: 3}, {value: 2, meta: 6}, {value: 3, meta: 9}]
    }
]
```

To save you from this manual effort, Chartist has a `data` event that allows you to transform your data before it gets used in Chartist.

Check the following example that solves your issue: http://jsbin.com/kanefa/2/edit?html,js,output

I think this is the most challenging data transformation requirement I've seen so far as a use-case for Chartist :-) I guess it would make sense to expose this total value somehow so that it's easier to access it. I'll flag this issue as enhancement.

**Comment by akhasis** [comment] 2015-05-18 06:56
Thank you! It worked like a charm, keep up the great work!

**Closed as completed** 2022-08-09 09:06 UTC
Labels: enhancement
