### ISSUE TITLE
Charts Inaccurate

### ISSUE THREAD

**Issue by fluffabelle** [chartist-js/chartist#199] opened 2015-02-20 17:59 UTC
I'm having issues with charts being inaccurately drawn. I removed all labelInterpolationFnc from the Y axis to show the issue. On the bar chart, the data value is 0.385 is being drawn around 0.365, it should be much higher.

On a line chart, the value 0.1186 is being drawn around 1.0, it is very far from where it should be.

**Comment by gionkunz** [comment] 2015-02-20 19:02
Can you post an example code to reproduce the issue? We mever had issues with inaccuracy. A JSBin that reproduces the issue would be great.

**Comment by fluffabelle** [comment] 2015-02-20 23:35
Sure, here you go: [link removed]
Thank you very much for the quick response!!

**Comment by danieldiekmeier** [comment] 2015-02-21 00:53
It seems to be related to very small values. Probably some kind of rounding error? I edited your example by multiplying all your values with 100 and everything seemed to be in order. If you need this _right now_, you could try multiplying the values before feeding them to Chartist, and interpolating the labels to show your original numbers again.

**Comment by fluffabelle** [comment] 2015-02-21 03:17
Yes, it does seem to be a small decimal issue. I multiplied all of the data points by 10 and it does appear to be accurate now.  Thank you for taking time to look into this!

**Comment by gionkunz** [comment] 2015-02-26 17:55
I'm debugging with your data but I can't reproduce the issue. Maybe it was related to version 0.5? 

Here's the bin I'm using: http://jsbin.com/punoce/1/edit?js,console,output

**Comment by fluffabelle** [comment] 2015-02-26 18:56
Gion, you are correct. I just plugged chartist 0.5 into your bin sample and it broke the data. I had a feeling deep down this would be a user error, haha :( I'm not sure how I got so far behind but I appreciate you taking the time to look!

**Comment by gionkunz** [comment] 2015-02-27 17:28
I'll close this issue for now. Please keep on posting if there are still open questions.

**Closed as completed by gionkunz** 2015-02-27 17:28 UTC
