### ISSUE TITLE
Create area which goes from value to value, not from 0 to value

### ISSUE THREAD

**Issue by mitar** [chartist-js/chartist#497] opened 2015-10-28 07:48 UTC
It seems currently it is possible to only create area which goes from 0 (or base) to some value. But I would need something from value to value. So that I can specify lower and higher values. Something like that:

![screen shot 2015-10-28 at 12 46 18 am](https://cloud.githubusercontent.com/assets/585279/10782429/8b990a50-7d0d-11e5-985e-2ff471c31ca4.png)

**Comment by gionkunz** [comment] 2015-12-11 15:12
Hi there, closing this issue as dupe of #322. Cheers

**Closed as completed by gionkunz** 2015-12-11 15:12 UTC
