### ISSUE TITLE
Key labels for axes

### ISSUE THREAD

**Issue by aaronik** [chartist-js/chartist#251] opened 2015-03-31 22:48 UTC
I have an awesome chart, thanks to you amazing folks making chartist:

![image](https://cloud.githubusercontent.com/assets/1324601/6930955/fd8638d2-d7bc-11e4-90da-c1fc465c65f1.png)

One problem that I'm running into is this: Can you tell me what this chart represents? You'd be able to if there were labels! It'd be great if the `options` had fields like `xLabel` and `yLabel` so I could label my chart here. I'd say `xLabel: courseVisits` and `yLabel: date` and you'd have a sense of what I'm trying to show here :smile:

**Comment by gionkunz** [comment] 2015-04-05 09:43
Hi there. This is a duplicate of #27 . I'm closing your issue in favor of #27 . Maybe we should reconsider to axis titles but I was always under the impression this could easily be done outside of chartist. Maybe we can discuss more in #27 ?

**Closed as completed by gionkunz** 2015-04-05 09:43 UTC

**Comment by aaronik** [comment] 2015-04-05 18:15
Oh yes, absolutely. I combed through the issues before I posted, not sure how I missed that, especially since it was so clearly named :) Thanks!
