### ISSUE TITLE
Wrong size when chart is rendered inside a transform

### ISSUE THREAD

**Issue by ivesklein** [chartist-js/chartist#1065] opened 2018-02-01 21:06 UTC
If i put the chart inside a element with scale transforms, the chart renders in wrong sizes.

https://codepen.io/ivesklein/pen/QQjVyV

**Comment by Arantiryo** [comment] 2022-10-29 12:20
Hello @ivesklein 👋 

Chartist has recently been updated to version `1.0` with some new exciting changes like ESM and TypeScript support. The migration guide can be found right [here](https://github.com/chartist-js/chartist#whats-new-in-v1).

Please let me know if the issue is still relevant to you so we can further investigate it!

**Comment by evertheylen** [comment] 2023-01-18 12:10
I have the same problem, with the latest version of chartist. I also made a codepen but it shows the exact same problem as @ivesklein: https://codesandbox.io/s/chartist-animation-size-t11sze

**Comment by evertheylen** [comment] 2023-01-18 13:54
I pushed a fix, but if you want to use/test this fix right now without waiting for this to be merged, you can monkey patch it easily:

```js
import { Svg } from "chartist";
Svg.prototype.width = function () {
  return this._node.clientWidth;
};
Svg.prototype.height = function () {
  return this._node.clientHeight;
};
```

**Closed as completed** 2023-01-31 08:27 UTC
