### ISSUE TITLE
How to define Y Axis Scale When Data passes dynamically

### ISSUE THREAD

**Issue by joshiashish23** [chartist-js/chartist#245] opened 2015-03-24 09:40 UTC
I am passing Points as below:

CategoryValuePointsArray : [12,15,12,45,78,10,12,4,5,13,20]

It Gives me : in fractions as 12.5,25,37.5...

Now I want Y axis like 10, 20 ,30......

How cna I do that, Is there any way to do it ?

**Comment by gionkunz** [comment] 2015-03-29 11:31
Hi There

This is a duplicate of #77 . I'm closing this issue in favor of 77. Let's track the progress on this there.

Cheers
Gion

**Closed as completed by gionkunz** 2015-03-29 11:31 UTC
Labels: duplicate
