### ISSUE TITLE
Line chart with tooltips demo creates multiple tooltips

### ISSUE THREAD

**Issue by ilanbiala** [chartist-js/chartist#138] opened 2015-01-09 21:35 UTC
The demo shows that only 1 tooltip should be created if I'm understanding the code, but there are about 20 and there are console errors when hovering on a point.

**Comment by gionkunz** [comment] 2015-01-10 19:45
Hey there. The example is fine. The problem is with the live code editing. As soon as you change the code it will not de-initialize the example properly leading to new tooltip elements being created. This would need to be fixed in the live example helper JavaScript.

**Comment by gionkunz** [comment] 2015-01-10 19:56
The example is kind of bad as it needs to fit onto the page with plenty of other examples. I appreciate a delegation approach over this. You can check the example on the smashing article http://www.smashingmagazine.com/2014/12/16/chartist-js-open-source-library-responsive-charts/ in the Extensibility chapter. Or directly check the JSBin used in the example: http://jsbin.com/seruk/edit?html,css,js,output

**Closed as completed** 2015-04-19 18:18 UTC
