### ISSUE TITLE
Pie chart - add an option to allow labels being oriented perpendicular/horizontal to the tangent lines

### ISSUE THREAD

**Issue by gsklee** [chartist-js/chartist#264] opened 2015-04-09 09:02 UTC
Demo: http://jsbin.com/jufuniniku/2/edit?html,js,output

Pie chart labels often overlap on top of each other, making things difficult to read. It would be helpful if an option can be implemented allowing the label texts to be placed horizontally (and/or perpendicularly) against the local tangents, so that the labels will looks like being radiated from the center point of the chart and won't overlap on top of each other.

**Comment by gionkunz** [comment] 2015-04-19 17:19
This is kind of a duplicate of #224 . We need to find a simple and nice way to solve this issue. Let's keep track of this in the earlier ticket.

**Closed as completed by gionkunz** 2015-04-19 17:19 UTC
