### ISSUE TITLE
Issues with class configuration parameter

### ISSUE THREAD

**Issue by jkoebner** [chartist-js/chartist#757] opened 2016-08-11 12:18 UTC
Hey there!

first of all thanks a lot for the library! Great work!

I wanted to inform you about an issue in the configuration. Some environments, routines, building processes and such have serious issues with the class keyword. In our example the minifying process crashed. Thus, all clientlibraries would not be built. Of course it makes sense to name it just the way it is named in html, however, it may lead to some conflicts. maybe you could add an additional configuration parameter (e.g. cssClass) that does the same but helps avoiding that problem.

In our case, however, it could also be avoided by quoting the class configuration parameter. Still, just wanted to let you know!

Kind regards and thanks again for your great work!!

**Comment by gionkunz** [comment] 2016-08-21 17:46
Duplicate of https://github.com/gionkunz/chartist-js/issues/455

**Closed as completed by gionkunz** 2016-08-21 17:46 UTC
