### ISSUE TITLE
Bar chart labels mis-aligned in IE?

### ISSUE THREAD

**Issue by hilary-L** [chartist-js/chartist#616] opened 2016-02-18 23:53 UTC
I've run across a strange issue with a bar chart in IE. In chrome, firefox, and safari, my bar chart looks like this:

![bar_chart_labels_chrome](https://cloud.githubusercontent.com/assets/8238197/13162121/42ebb122-d668-11e5-9b2b-9d72d06d6d51.png)

But in IE 9/10/11 the bar chart looks like this:

![bar_chart_labels_ie](https://cloud.githubusercontent.com/assets/8238197/13162130/51756ecc-d668-11e5-8ad9-f8569969e50a.jpg)
(arrows added to point out the label problem)
I can't figure out why the labels are misaligned in IE. Is this a problem with foreignobject support? Is there a way to fix it?

**Comment by gionkunz** [comment] 2016-02-22 07:54
Duplicate of #54

**Closed as completed by gionkunz** 2016-02-22 07:54 UTC
