### ISSUE TITLE
Tooltip example: position off in Firefox

### ISSUE THREAD

**Issue by tirdadc** [chartist-js/chartist#418] opened 2015-08-25 15:53 UTC
https://gionkunz.github.io/chartist-js/examples.html#line-chart-with-tooltips

![tooltip](http://i.imgur.com/0k4LI20.png)

The positioning works fine in Chrome, but it seems to be off in Firefox.

**Comment by gionkunz** [comment] 2015-08-25 17:36
Hi there, sorry for that. This is a duplicate of #381 and will be resolved with #419

**Closed as completed by gionkunz** 2015-08-25 17:36 UTC
