### ISSUE TITLE
Gauge chart with a pointer

### ISSUE THREAD

**Issue by hugovk** [chartist-js/chartist#717] opened 2016-06-15 12:00 UTC
Is it possible to create a [gauge chart](https://gionkunz.github.io/chartist-js/examples.html#simple-gauge-chart) with a (labelled) line on the top, something along the lines of this?

![image](https://cloud.githubusercontent.com/assets/1324225/16078727/24203d14-3309-11e6-9d28-a5f56b3b3eda.png)

**Comment by gionkunz** [comment] 2016-06-22 08:00
Duplicate of https://github.com/gionkunz/chartist-js/issues/589

**Closed as completed by gionkunz** 2016-06-22 08:00 UTC
