### ISSUE TITLE
LINE Chart Labels Rotation Problem in Chrome

### ISSUE THREAD

**Issue by n-sagi** [chartist-js/chartist#905] opened 2017-03-04 22:07 UTC
Hi there!

I have a problem with the horizontal (X) axis labels in LINE chart.  In my application X axis labels are words, and in their default horizontal position, each label is overlapping with its neighbors. Hence, in order to isolate the problem, and based on the ["getting starting" examples](https://gionkunz.github.io/chartist-js/getting-started.html#as-simple-as-it-can-get), I added the following custom CSS:
```
.ct-label.ct-horizontal.ct-end{
	position: relative;
	right: 10px;
	top: 10px;
    -ms-transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
	filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
    transform: rotate(45deg);
}
```
The problem is that the X axis labels rotation is as expected in Firefox (checked version 53.0a2 64-bit) and Edge (checked version 38.14393.0.0), 
![labels](https://cloud.githubusercontent.com/assets/26191252/23582618/03259b20-0137-11e7-90f0-ae219fc2057e.png)
but is in a really mesh in Chrome (checked version 56.0.2924.87 64-bit).
![labelschrome](https://cloud.githubusercontent.com/assets/26191252/23582619/0b48b83c-0137-11e7-8761-22ef0b6f6a65.png)
Please also check [jsfiddle here](https://jsfiddle.net/tikhonovits/9z1a0gm4/).

Are there any ideas about how the above problem can be fixed?

Thanks,
Nikos

**Comment by gionkunz** [comment] 2017-03-14 08:14
Hi there, this is a possible duplicate of #712 please re-open if that didn't help

**Closed as completed by gionkunz** 2017-03-14 08:14 UTC
