### ISSUE TITLE
Improving "How to use plugins" documentation

### ISSUE THREAD

**Issue by sebkkom** [chartist-js/chartist#461] opened 2015-09-24 16:54 UTC
Hello and thank you very much everyone that has contributed for chartist,

I am openning this issue as I'd like to discuss a possible improvement in the plugins documentation:

The "How to use plugins" section starts with _Once you have included a plugin in your project_ and takes it for granted that users know this means downloading the plugin, moving the appropriate files to the appropriate folder and including the scripts in the code. But, to a beginner with bower and the rest (like me, for example), these are not very clear (and I am still not sure I've done everything right). It also gets even more confusing when somebody looks at the `tooltip` plugin [github page](https://github.com/Globegitter/chartist-plugin-tooltip) and reads `bower install chartist-plugin-tooltip --save`, assuming this is enough to "include" the plugin.

If you think the section can be improved I would be more than happy to go ahead and make a pull request with some more detailed instructions as written above.

**Comment by gionkunz** [comment] 2015-09-24 17:21
Your contribution would be very much appreciated!

**Comment by gionkunz** [comment] 2015-09-24 17:21
And I agree this could be explained in much more detail

**Comment by swiharta** [comment] 2017-10-17 23:55
Desperately wish I knew how to use the plugins with Chartist in a Webpack + Babel / ES6 build environment. `import Chartist from 'chartist'` works fine. Then I have no idea how to get `Chartist.plugins.ctThreshold` into my project.  Do you have to use script tags? `Chartist.plugins` is undefined. Any help much appreciated!

**Comment by swiharta** [comment] 2017-10-18 12:54
Had to add `import Chartist from 'chartist'` to the top of the `chartist-plugin-threshold.js` file. Getting odd behavior with that one though, threshold seems to get set correctly for the first of multiple charts on the same page, the others have the threshold set to the same "height" on the chart with no relation to the values on the y-axis. Seem likely because I'm drawing multiple charts to the same page.

**Comment by corizoqo** [comment] 2018-12-24 17:31
Hi,
could you help me with the plugins? I have the following code in my head section:
```
<script src="dist/chartist.min.js"></script>
<script src="dist/chartist-plugin-tooltip.js"></script>
```
I don't use bower or anything, just downloaded the dist directory from Chartist and the plugin, added it to the head as you can see. The default examples work, but if I use the example of the tooltip plugin, there are no tooltips in the chart, but there is an error:
```
Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at Object.c.createSvg (chartist.js:330)
    at f.d [as createChart] (chartist.js:3355)
    at f.h (chartist.js:1925)
```
This is my dist directory content:

chartist-plugin-tooltip
chartist-plugin-tooltip.css
chartist-plugin-tooltip
chartist-plugin-tooltip.min
chartist-plugin-tooltip.min.js
chartist
chartist.css
chartist
chartist.min
chartist.min
chartist.min.js
LICENSE
scss

**Comment by rodhoward** [comment] 2019-04-30 04:22
For those that read this thread and still haven't found a usefull reference. Here is what seems to be working for me.

1. install plugin via npm e.g. `npm install chartist-plugin-pointlabels --save`
1. register plugin with chartist:

   ```javascript
   import Chartist from "chartist";
   // some pain points here bar plugin needed it declared on the window :(
   window["Chartist"] = Chartist;

   const pointLabels = require("chartist-plugin-pointlabels");
   const barLabels = require("chartist-plugin-barlabels");

   pointLabels();
   barLabels();
   ```

1. use the plugin in your chart

   ```javascript
   const chartConfig = {
     plugins: [
       Chartist.plugins.ctPointLabels({
         textAnchor: "middle",
         labelOffset: {
           x: 0,
           y: -10
         },
         labelInterpolationFnc: value => value || ""
       })
     ]
   };
   ```

**Comment by tobycatlin** [comment] 2019-05-21 14:31
I have just hit this problem. I cannot see how to install a plugin and am not using Node.

**Comment by BojidarStanchev** [comment] 2019-09-18 14:48
Hey, I know this probably isn't the place, but do you have any idea how to add chartist plugins if I'm using the Retyped.chartist mappings for .Net? You can answer here: https://stackoverflow.com/questions/57790720/how-to-load-and-use-chartist-plugins-when-using-retyped-mappings so we don't spam this issue.

**Comment by jeremycherfas** [comment] 2020-12-27 14:57
I'd like to suggest that references to Bower be changed to, perhaps, npm. I installed a plugin with Bower and had an error that was caused by Bower using an old version. The plugin, to its credit, said use npm but I used Bower because that is what Chartist said to use.

**Comment by gionkunz** [comment] 2022-08-09 09:15
We have recently updated the stack and backbone of Chartist, and we're ready again to work on enhancements and plugins. We will need to rethink the v1.0.0 plugin mechanism again and how to support legacy plugins. Closing this, for now, if there's still a need for fixes, please open a discussion again.

**Closed as completed by gionkunz** 2022-08-09 09:15 UTC
Labels: enhancement, documentation
