### ISSUE TITLE
donut chart not rendered correctly if ratio between first and second value is very small

### ISSUE THREAD

**Issue by samuelcambien** [chartist-js/chartist#527] opened 2015-11-27 12:50 UTC
If the ratio between the first and the second value for a donut chart data is smaller than 0,056%, the donut chart isn't rendered correctly. This seems related to issue https://github.com/gionkunz/chartist-js/issues/265, where a similar problem occured when one of the data values was zero. That issue is fixed by now, but the problem remains in case the data ratio is too small.
![screen shot 2015-11-27 at 12 03 27](https://cloud.githubusercontent.com/assets/11772282/11439957/e7a2d1ec-94fe-11e5-9988-176dbc9d2edb.png) ![screen shot 2015-11-27 at 13 44 02](https://cloud.githubusercontent.com/assets/11772282/11441507/fb98169a-950c-11e5-928c-ad951f2da6a3.png)

**Comment by hansmaad** [comment] 2015-12-16 09:25
@gionkunz I'm working on this. Do you remember the reason for the modification of startAngle here

```
      var start = Chartist.polarToCartesian(center.x, center.y, radius, 
          startAngle - (i === 0 || hasSingleValInSeries ? 0 : 0.2));
```

0.2 leads to negative startAngle. All tests pass and all examples look fine if I comment out this part. Do we really need this?

fix / test: https://github.com/hansmaad/chartist-js/commit/d4fe5100ca6695a26a71d140a8af80881e0e1606

**Comment by gionkunz** [comment] 2015-12-16 14:31
I think this is coming from a fix when data with 0 was passed in. Can you check the git history? I'll check later and post my findings.

**Comment by hansmaad** [comment] 2015-12-16 14:38
@gionkunz It's part of the first commit :-D
https://github.com/gionkunz/chartist-js/commit/9db458efe1122885434f010bfef792244cc2584b#diff-96ca44095a13ebcf6b90d06c5e6316e2R68

**Comment by gionkunz** [comment] 2015-12-16 14:49
:-) Hmmm... Yeah, and now I'm recollecting why it's there. The problem is with that if you remove this, you notice a gap between the slices because of rounding issues. The `0.2` provides a little overlap so there is no gap. This is a common problem in vector graphics and also a practice when drawing vector images. It will be a challenge to write tests for this :-/. We should add sufficient comments. What if we limit with `Math.max(0, startAngle)`?

**Comment by gionkunz** [comment] 2015-12-16 14:58
I guess this could then be simplified to:

``` javascript
  var start = Chartist.polarToCartesian(center.x, center.y, radius, Math.max(0, startAngle - 0.2));
```

**Comment by hansmaad** [comment] 2015-12-16 15:27
I think it's not that hard to test. I'll have a look on this tomorrow and make a pr.

**Comment by hansmaad** [comment] 2015-12-17 09:56
I fixed this and some other issues in https://github.com/hansmaad/chartist-js/commit/ec00b726030a8b5ec90b263a0cca7a65dc98b4f3 (Tested in Chrome, IE11, FF on Win7)

There is one potential issue left with full arc 359.99 hack which is currently not closed, but I can't see any gaps in examples. I didn't find a way to close a subpath with `Chartist.Svg.Path`

**Comment by gionkunz** [comment] 2015-12-17 22:37
Epic! Thanks for this. Yeah, with hard to test I was referring to testing if there is a small visible gap between the donut / pie segments. I think there's no way to have two paths closing together. The Z argument is only for closing single paths and forming a loop. I'll also do a few tests on your commit.

**Closed as completed** 2016-01-06 16:26 UTC
