### ISSUE TITLE
Performance Issue?

### ISSUE THREAD

**Issue by examinedliving** [chartist-js/chartist#721] opened 2016-06-17 21:25 UTC
I was all set to use this for a website I'm developing, and then my computer started moving very slowly.  After some investigation, I discovered that the source of the problem was the Chartist website tab.  That tab alone was using between 27 and 45% CPU. 

I thought it was a memory leak, so I checked the error console (nothing); updated my browser, and tried several different re-launches all to the same effect.  I don't know if it has something to do with my computer, maybe an extension I have installed; or maybe something else.  Either way, until I resolve this for myself, it's kind of a deal-breaker.  Perhaps you can shed some insight on this?

I'm using `Chrome 53.0.2767.5 dev-m (64-bit)` - also whatever the version was immediately prior this had the same problem.

Thanks.

**Comment by gionkunz** [comment] 2016-06-17 21:29
Without render updates Chartist shouldnt use any of your cpu. Maybe you can share your code?

**Comment by examinedliving** [comment] 2016-06-17 21:50
I'm happy to hear that.  The issue happens when visiting the  [chartist.js website](http://gionkunz.github.io/chartist-js/).  I have the problem just visiting the site and looking at the examples page.  Perhaps some browser bug?

**Comment by gionkunz** [comment] 2016-06-22 06:18
Well, this page is very cluttered with examples that sometimes use large amount of data and also use timeouts to re-render some of the examples for illustration purpose. I suppose it's normal that this page requires some CPU time. When looking at the profiler there's a `setAttribute` caused by the examples on 11 elements which causes a re-layout and therefore some CPU demand. However, I think this is really only how the examples page is set up. I'll close this issue for now until we have a real use-case where performance issues exist.

**Closed as completed by gionkunz** 2016-06-22 06:18 UTC

**Comment by kalnode** [comment] 2024-03-20 14:33
This is vague: "Chartist website tab"

What page exactly?

If it's a demo page full of iframes loading external code sandboxes... then yea... that's going to be a heavy page. If this is the case, then it's not a Chartist-library issue... it's a Chartist-demo-webpage-that's-full-of-iframes issue.
