### ISSUE TITLE
Bar chart not working with ajax recieved data

### ISSUE THREAD

**Issue by alexpavel** [chartist-js/chartist#485] opened 2015-10-17 16:07 UTC
Hello,

I am trying to update the barchart from an ajax response and it doesn't work.

My ajax strings look like this:

For labels: 'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'

For series: [3,6,5,9,5,9,9,5,7,7,3,6],[2,3,2,8,10,10,1,6,4,1,9,1],[3,7,5,7,10,9,8,2,5,4,5,10],[7,2,4,8,6,8,5,8,3,1,2,10]

My code for them is like this
var data = {  
  labels: [labels],
  series: [chartData]
};

The chart show's the labels, but I get this error d.normalized[e].forEach is not a function, how can I fix this?

Thank you!

**Comment by gionkunz** [comment] 2015-10-19 13:44
Hi there. There must be something wrong with the JSON reply from your server. Please check again or post the JSON reply. Cheers

**Comment by DaneNutting** [comment] 2015-11-02 12:30
No problems using JSON data to populate graphs here.

**Comment by gionkunz** [comment] 2015-12-22 08:19
Did you found a solution to your problem yet?

**Comment by ashishsajwan** [comment] 2016-04-06 06:56
@alexpavel 
series should be array of array..
For series: [ [3,6,5,9,5,9,9,5,7,7,3,6],[2,3,2,8,10,10,1,6,4,1,9,1],[3,7,5,7,10,9,8,2,5,4,5,10],[7,2,4,8,6,8,5,8,3,1,2,10] ]

and labels should also be array of values 
For labels:  [ 'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec' ]
@DaneNutting @gionkunz

**Comment by jassuncao** [comment] 2016-10-07 20:41
I think the issue might me caused by the use of multiple context (e.g. frames or windows).
If the data is fetched in a context different from the one where the chart is rendered recursiveConvert(value) will fail. There is a test that checks if value is an array and this will fail because instanceof returns false if the array instance is from another context.

**Comment by gionkunz** [comment] 2016-10-17 19:30
I'll close this issue, please re-open if needed

**Closed as completed by gionkunz** 2016-10-17 19:30 UTC

**Comment by kashifnawaz77** [comment] 2017-02-11 07:25
function bookingscount()
    {
      //dblogic
        $response = array();
        $response["labels"] = array();
        $response["series"] = array();        
        $responseseries = array();//for saving all series values in arrray and passing it in response array
        foreach ($result as $key) { //$results = array from db           
           array_push($response["labels"], $key['bookingdate']);
           array_push($responseseries,$key['bookings']);
        }
       array_push($response["series"],$responseseries);//coz chart api wanted series objects in nested array
      echo json_encode($response,JSON_NUMERIC_CHECK); 
    }


Ajax methood

success : function(data) {			
					var cdata = JSON.parse(data);
			    	new Chartist.Bar('#chart2', {
					  labels: cdata['labels'],
					  series: cdata['series']
					});
			    }
