### ISSUE TITLE
Graph printing

### ISSUE THREAD

**Issue by brandondv** [chartist-js/chartist#166] opened 2015-01-28 10:39 UTC
Hey, 
First of all, thank you for this great tool!

I only have only one remark/problem.
It works fine on all my digital devices but when printed it doesn't center and cuts of the right-side and bottom of the graphs... 
Is this fixable?
![screen shot 2015-01-28 at 11 36 16](https://cloud.githubusercontent.com/assets/10170446/5936130/ef57fd92-a6e1-11e4-8559-1ec4ae0177fa.png)
^this is the page when printed
![screen shot 2015-01-28 at 11 38 12](https://cloud.githubusercontent.com/assets/10170446/5936162/2fccffee-a6e2-11e4-8359-14f314ae3358.png)
^This is how the browser renders it

**Comment by gionkunz** [comment] 2015-01-30 21:20
Hi there, this is a duplicate of #118 . Lets keep track there! Thanks

**Closed as completed by gionkunz** 2015-01-30 21:20 UTC
