### ISSUE TITLE
Custom text inside donut chart

### ISSUE THREAD

**Issue by ghost** [chartist-js/chartist#706] opened 2016-05-31 16:40 UTC
I need to add some custom text inside the donut chart as seen below:
http://i.imgur.com/tBrkNpc.png

The total value needs to show the total of donut chart values. What is the best way to do this?

**Comment by simas93** [comment] 2016-06-03 10:17
if you don't need animated donut, trys this plugin https://github.com/moxx/chartist-plugin-fill-donut

**Comment by gionkunz** [comment] 2016-10-19 10:53
Duplicate of #255

**Closed as completed by gionkunz** 2016-10-19 10:53 UTC
