### ISSUE TITLE
Incorrect series attribute locks up browser

### ISSUE THREAD

**Issue by sherzberg** [chartist-js/chartist#242] opened 2015-03-20 21:01 UTC
Not sure if this is a bug or just a documentation issue, but I accidentally set my `series` attribute to an array of ints and chrome and firefox just locked up to the point where I could'nt close the chrome tab or the entire browser. Is a datatype check possible to throw an error instead of locking up?

``` javascript
var data = {
  // A labels array that can contain any sort of values
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  // Our series array that contains series objects or in this case series data arrays
  series: [5, 2, 4, 2, 0]
};
```

**Comment by gionkunz** [comment] 2015-03-29 11:40
Can you post the full example? 

I can't reproduce this with the following code:

``` javascript
new Chartist.Line('.ct-chart', {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  series: [5, 2, 4, 2, 0]
});
```

**Comment by aaronik** [comment] 2015-03-31 22:00
This may not be of much help, but I'm noticing that my browser locks up quite a bit when I specify bad values. For example, `high`s that are lower than `low`s, a `height: 10px`, and others that I can't remember ATM.

```
$ uname -a
Linux 3.16.0-33-generic #44~14.04.1-Ubuntu SMP Fri Mar 13 10:33:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ chromium-browser --version
Chromium 41.0.2272.76 Ubuntu 14.04
```

**Comment by gionkunz** [comment] 2015-04-26 15:31
Relates to #292

**Comment by gionkunz** [comment] 2015-04-26 16:00
I'll close this issue. If this issue reoccures and can be reproduces we can start a discussion again. Cheers

**Closed as completed by gionkunz** 2015-04-26 16:00 UTC
