### ISSUE TITLE
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated 

### ISSUE THREAD

**Issue by Maxhodges** [chartist-js/chartist#521] opened 2015-11-21 17:18 UTC
I get this error when pasting the FILLDONUT PLUGIN example

SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

**Comment by gionkunz** [comment] 2015-11-30 10:26
Hi there, this is a duplicate of #468. Thanks for the report though!

**Closed as completed by gionkunz** 2015-11-30 10:26 UTC
